# Generated by Django 5.1 on 2024-08-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cliente_questoes_feitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='alternativas',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.questao'),
        ),
        migrations.RemoveField(
            model_name='questao',
            name='categoria',
        ),
        migrations.AddField(
            model_name='questao',
            name='categoria',
            field=models.ManyToManyField(to='api.categoria'),
        ),
    ]
