# Generated by Django 5.1 on 2024-08-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_questao_alternativas_alternativa_questao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questao'),
        ),
    ]
